# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.controller.category_controller:
    class: AppBundle\Controller\CategoryController
    autowire: true
  app.controller.homepage_controller:
    class: AppBundle\Controller\HomepageController
    autowire: true
  app.controller.product_controller:
    class: AppBundle\Controller\ProductController
    autowire: true

